import "./globals.css";

export const metadata = {
  title: "Archetopia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins"
          rel="stylesheet"
        />
      </head>
      <body className="h-screen w-full overflow-y-hidden flex justify-center bg-linear-180 from-neutral-900 to-slate-900 text-neutral-300 relative">
        {children}
      </body>
    </html>
  );
}
