import "./globals.css";
import Layout_1 from "@/components/Layout_1";
import Navbar from "@/components/package/Navbar";
import Content_2 from "@/components/Content_2";
import Sidebar from "@/components/package/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins"
          rel="stylesheet"
        />
      </head>
      <body className="w-full flex justify-center bg-neutral-50 relative">
        <Layout_1>
          <main className="h-screen flex flex-col">
            <section className="flex-none">
              <Navbar></Navbar>
            </section>
            <section className="flex-1">
              <Content_2 sidebar={<Sidebar></Sidebar>}>
                <main className="p-10">{children}</main>
              </Content_2>
            </section>
          </main>
        </Layout_1>
      </body>
    </html>
  );
}
